### ISSUE TITLE
Align with uBo scriptlets and resources standards

### ISSUE THREAD

**Issue by seia-soto** [ghostery/adblocker#4392]
Currently, there're some behaviors that mismatches with uBo: https://github.com/gorhill/uBlock/wiki/Resources-Library . This issue tries to list capabilities that mismathces/unsupported by our adblocker engine. If you have any ideas, please let us know.

We're trying to be close in ad-blocking and filter parsing capabilities as uBo does.

## Ongoing roadmap

```[tasklist]
### Tasks
- [ ] https://github.com/ghostery/adblocker/pull/4270
- [ ] https://github.com/ghostery/adblocker/pull/4376
- [ ] https://github.com/ghostery/adblocker/pull/4394
```

### Do not skip .js when the scriptlet is used with redirect=, only when used in +js(...).

refs https://github.com/ghostery/adblocker/issues/4393

### Parsing object in the scriptlet arguments

We currently parse objects in the scriptlet arguments. For an instance, the following will be regarded as an argument: `{ "a": 1, "b": 1 }`. However, it's not a valid scriptlet arugment since you didn't escaped a comma. We'll drop this object parsing capability in short and try to take some performance headrooms.

### You should omit the .js from the scriptlet name in scriptlet injection filters (eventually in some future this will be the official way to do this).

Since [v1.34](https://github.com/ghostery/adblocker/releases/tag/v1.34.0), we shipped JSON based resources format. This was to support aliasing and more properly, but changed the behavior slightly. Currently, we're handling non-suffixed scriptlet calls by suffixing `.js` extension.
- If a scriptlet name has a suffix of `.js`, we'll query as-is.
- If a scriptlet name has no suffix of `.js`, we'll query with `.js` suffix.

From uBo documentation, it says that we should omit the `.js` extension. We won't drop support for scriptlet calls without an file extension for now, but we'll drop it when uBo will.

### The only filter lists deemed from a "trusted source" are uBO-specific filter lists (i.e. "uBlock filters -- ..."). The user's own filters from "My filters" are trusted only in the dev build of uBO. This behaviour can be overridden with the advanced setting trustedListPrefixes.

We're looking for a best way to implement "trusted sources" and give users a choice. Nothing has been decided so far but we expect users will able to have a feature flag that enables/disables trusted resources, scriptlets, and filters.

### Mime type is application/javascript if not present.

We currently don't see a critical breakage regarding this. However, we'll need to decide how an adblocker will react in the future.
